Changes in docs/source/tasks files
hyperledger-labs/fabric-ansible-collection pull request #19
Opened 2023-06-22 12:01 UTC by shubhamshukla25

Changes made to the folder docs/source/tasks

2023-06-22 14:24 UTC, modemn commented on docs/source/tasks/intermediateCA.rst
> +IBM Support for Hyperledger Fabric allows for the optional use of Intermediate CAs which can protect a root CA and provide operational flexibility. The IBM Support for Hyperledger Fabric documentatio
Similar thing here, need to generalise the wording since this applies to the Fabric OSS as well

2023-06-22 14:25 UTC, modemn commented on docs/source/tasks/intermediateCA.rst
> +IBM Support for Hyperledger Fabric allows for the optional use of Intermediate CAs which can protect a root CA and provide operational flexibility. The IBM Support for Hyperledger Fabric documentatio
Also might want to get rid of the reference to the documentation since this is a Hyperledger Fabric repo

2023-06-22 14:29 UTC, modemn requested changes
All the links for the playbooks also still point to the IBM-Blockchain/ansible-collection repo which should be changed to the new collection repo.

2023-06-26 09:15 UTC, modemn requested changes

2023-06-26 09:15 UTC, modemn commented on docs/source/tasks/intermediateCA.rst
> +This task guide assumes that you have access to the IBM Support for Hyperledger Fabric documentation and the sections regarding Intermediate CAs.
I think we can just get rid of this line.

2023-06-26 09:15 UTC, modemn commented on docs/source/tasks/addadmincert.rst
> +  Review the example playbook `05-update-channels-admin.yml <https://github.com/IBM-Blockchain/fabric-ansible-collection/blob/main/examples/add-admin-cert/05-update-channels-admin.yml>`_, then run it
```suggestion
  Review the example playbook `05-update-channels-admin.yml <https://github.com/hyperledger-labs/fabric-ansible-collection/blob/main/examples/add-admin-cert/05-update-channels-admin.yml>`_, then run it as follows:
```

2023-06-26 09:41 UTC, shubhamshukla25 commented on docs/source/tasks/intermediateCA.rst
> +Hyperledger Fabric allows for the optional use of Intermediate CAs which can protect a root CA and provide operational flexibility. The  Hyperledger Fabric CA documentation describes the business rer
Changes committed as per the review comments

2023-06-26 09:42 UTC, shubhamshukla25 commented on docs/source/tasks/update-channel-parameters.rst
> +Hyperledger Fabric allows each channel to be configured with specific BatchSize parameters and a BatchTimeout for blocks.  This playbook example shows how an Architect or Chaincode Developer could to
Changes committed as per the review comments

2023-06-26 10:13 UTC, modemn approved these changes

2023-06-26 12:38 UTC, merged